version: "3"

services:

  maciel-web:
    build: 
        context: ./
        dockerfile: Dockerfile
    image: php:8.0-apache
    container_name: maciel-web
    ports:
      - "81:80"
    networks: 
     - maciel-network
    volumes:
      - ./:/var/www/html
      - ./config/apache2:/etc/apache2/sites-enabled
      - ./config/certs:/etc/apache2/certs
    depends_on:
      - maciel-mysql

  maciel-mysql:
    image: mysql:8.0
    container_name: maciel-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dckr_pat_s4V2Q-vYX_-0LadMkLQIO_OcOvo
      MYSQL_DATABASE: whatsapp
      MYSQL_USER: bot
      MYSQL_PASSWORD: dckr_pat_s4V2Q-vYX_-0LadMkLQIO_OcOvo
    ports:
      - "3366:3306"
    networks: 
     - maciel-network
    volumes: 
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./data/db:/var/lib/mysql

networks: 
  maciel-network: 
    driver: bridge